apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: queue-service

resources:
  - deployment.yaml
  - service.yaml
  - hpa.yaml

labels:
  - pairs:
      app.kubernetes.io/name: queue-service
      app.kubernetes.io/component: queue
      app.kubernetes.io/part-of: morupark-msa