apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: morupark-dev
resources:
  - namespace.yaml
  - configmap.yaml
  - secret-provider-class.yaml
  - morupark-sql-config.yaml
  - secret-store.yaml
  - external-secret.yaml