apiVersion: v1
kind: ConfigMap
metadata:
  name: morupark-sql-config
  namespace: morupark-dev # This will be overridden by overlays
data:
  SQL_INSTANCE_CONNECTION_NAME: yourssu-morupark:asia-northeast3:morupark-db-public
