apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: morupark-dev
  labels:
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/component: auth
    app.kubernetes.io/part-of: morupark-msa
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8081
    targetPort: http
    protocol: TCP
  selector:
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/component: auth