apiVersion: v1
kind: Service
metadata:
  name: queue-service
  namespace: morupark-dev
  labels:
    app.kubernetes.io/name: queue-service
    app.kubernetes.io/component: queue
    app.kubernetes.io/part-of: morupark-msa
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8082
    targetPort: http
    protocol: TCP
  selector:
    app.kubernetes.io/name: queue-service
    app.kubernetes.io/component: queue
