apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: morupark-base

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: morupark-msa
      app.kubernetes.io/managed-by: kustomize